const express = require("express")
const { register, verify, login, logout,getMyProfile, updateProfile, updatePassword, forgetPassword, resetPassword } = require("../controllers/User")
//const verify = require("../controllers/User")
const isAuthenticated = require("../middleware/auth")
const router = express.Router() 
router.route("/register").post(register)
router.route("/verify").post(isAuthenticated, verify)
router.route("/login").post(login)
router.route("/logout").get(logout)
router.route("/getMyProfile").get(getMyProfile)
router.route("/updateprofile").put(isAuthenticated, updateProfile)
router.route("/updatepassword").put(isAuthenticated, updatePassword)
router.route("/forgetpassword").post(forgetPassword)
router.route("/resetpassword").put(resetPassword)
module.exports = router